language: python

sudo: false

matrix:
    include:
        - python: '2.5'
        - python: '2.6'
        - python: '2.7'
        - python: '3.1'
        - python: '3.2'
        - python: '3.3'
        - python: '3.4'
        - python: '3.5'
        - python: '3.6'
        - python: 'nightly'
        - python: 'pypy'
        - python: 'pypy3'
    allow_failures:
        - python: '2.5'
        - python: '2.6'
        - python: '3.1'
        - python: '3.2'
        - python: '3.3'
        - python: 'nightly'
        - python: 'pypy3'
    fast_finish: true

cache:
    pip: true

before_install:
    - set -e  # fail on any error

install:
    - python setup.py build && python setup.py install

script:
    - for test in tests/*.py; do echo $test ; python $test > /dev/null ; done
